[project]
name = "lockr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bcrypt>=5.0.0",
    "cryptography>=46.0.3",
    "pyperclip>=1.11.0",
    "rich>=14.2.0",
]
